services:
  mongodb:
    image: mongo:8
    container_name: finance-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - finance_mongo_data:/data/db
volumes:
  finance_mongo_data:
